
sudo: false # route build to the container-based infrastructure for a faster build

language: node_js
node_js:
  - 'node' # implies latest version

cache:
  directories:
    - node_modules
    - fullcalendar # a checkout of the core repo

before_install: bin/install-core-repo.sh

env:
  global:
    - TZ="America/Los_Angeles" # for Headless Chrome. otherwise will be UTC, bad for tests
  matrix:
    - CMD=lint
    - CMD=test
    - CMD=test-side-effects

# TODO: instead of flag, use env variable TRAVIS
# https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
script: npm run $CMD -- --travis
