language: node_js
node_js:
  - 'node' # implies latest version

cache:
  directories:
    - node_modules
    - fullcalendar

before_install: bin/install-core-repo.sh

env:
  - CMD=test
  - CMD=lint

script: npm run $CMD
